# Generated by Django 5.2 on 2025-04-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo_projeto', models.CharField(choices=[('com_dump', 'Com Dump Automático'), ('sem_dump', 'Sem Dump')], max_length=10)),
                ('caminho_media', models.CharField(help_text='Caminho para o diretório de mídia a ser backupeado.', max_length=255)),
                ('caminho_docker_compose', models.CharField(blank=True, help_text='Caminho para o docker-compose.yaml, se necessário.', max_length=255, null=True)),
                ('tipo_banco', models.CharField(default='PostgreSQL', max_length=50)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
