# Generated by Django 5.2 on 2025-04-29 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_alter_projeto_tipo_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_backup', models.PositiveSmallIntegerField(choices=[(1, 'Com dump de banco de dados'), (2, 'Apenas via rsync')])),
                ('caminho_bases_dados', models.CharField(blank=True, help_text='Usado no Tipo 2', max_length=255, null=True)),
                ('banco_host', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_senha', models.CharField(blank=True, max_length=100, null=True)),
                ('ssh_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ssh_porta', models.PositiveIntegerField(default=22)),
                ('destino_backup', models.CharField(max_length=255)),
                ('manter_permissoes', models.BooleanField(default=True)),
                ('deletar_arquivos_remotos', models.BooleanField(default=False)),
                ('horario_execucao', models.CharField(help_text='Horário(s) no formato crontab ou texto', max_length=100)),
                ('dias_reter_backup', models.PositiveIntegerField(default=7)),
                ('ignorar_arquivos', models.TextField(blank=True, help_text='Um por linha', null=True)),
                ('email_notificacao', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='setup.projeto')),
            ],
            options={
                'verbose_name': 'Configuração do backup',
                'verbose_name_plural': 'Configurações dos backups',
            },
        ),
    ]
