# Generated by Django 5.2 on 2025-04-29 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_configuracaobackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaobackup',
            name='banco_host',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco host'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='banco_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco nome'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='banco_senha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco senha'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='banco_usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco usuário'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='caminho_bases_dados',
            field=models.CharField(blank=True, help_text='Usado apenas ao selecionar o tipo rsync', max_length=255, null=True, verbose_name='Caminho da base de dados'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='deletar_arquivos_remotos',
            field=models.BooleanField(default=False, verbose_name='Deletar arquivos remotos'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='destino_backup',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho destino do backup'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='dias_reter_backup',
            field=models.PositiveIntegerField(default=7, verbose_name='Dias retenção de backup'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='email_notificacao',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail (para envio de notificações)'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='horario_execucao',
            field=models.CharField(blank=True, help_text='Horário(s) no formato crontab ou texto', max_length=100, null=True, verbose_name='Horário de execução'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='ignorar_arquivos',
            field=models.TextField(blank=True, help_text='Um por linha', null=True, verbose_name='Arquivos a serem ignorados'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='manter_permissoes',
            field=models.BooleanField(default=True, verbose_name='Manter permissões'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='setup.projeto', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='ssh_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP SSH'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='ssh_porta',
            field=models.PositiveIntegerField(blank=True, default=22, null=True, verbose_name='Porta SSH'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram chat id (para envio de notificações)'),
        ),
        migrations.AlterField(
            model_name='configuracaobackup',
            name='tipo_backup',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Com dump de banco de dados'), (2, 'Apenas via rsync')], verbose_name='Tipo de backup'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='caminho_docker_compose',
            field=models.CharField(blank=True, help_text='Caminho para o docker-compose.yaml, se necessário.', max_length=255, null=True, verbose_name='Caminho do docker compose'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='caminho_media',
            field=models.CharField(help_text='Caminho para o diretório de mídia a ser backupeado.', max_length=255, verbose_name='Caminho das midias'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo_banco',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('sqlite3', 'SQLite3')], default='PostgreSQL', max_length=50, verbose_name='Tipo do banco'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo_projeto',
            field=models.CharField(choices=[('com_dump', 'Com Dump Automático'), ('sem_dump', 'Sem Dump')], max_length=10, verbose_name='Tipo do projeto'),
        ),
        migrations.CreateModel(
            name='ExecucaoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de término')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('executando', 'Executando')], max_length=20, verbose_name='Status da execução')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem / log')),
                ('duracao', models.DurationField(blank=True, null=True, verbose_name='Duração')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='setup.configuracaobackup', verbose_name='Configuração do backup')),
            ],
            options={
                'verbose_name': 'Execução do backup',
                'verbose_name_plural': 'Execuções dos backups',
            },
        ),
    ]
