# Generated by Django 5.2 on 2025-04-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_alter_configuracaobackup_banco_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(help_text='Pode ser um horário fixo (ex: 03:00) ou expressão crontab (ex: 0 3 * * *).', max_length=100, verbose_name='Horário de execução')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='setup.configuracaobackup', verbose_name='Configuração do backup')),
            ],
            options={
                'verbose_name': 'Agendamento do backup',
                'verbose_name_plural': 'Agendamentos dos backups',
            },
        ),
        migrations.CreateModel(
            name='LogExecucaoDetalhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('stdout', 'Saída padrão'), ('stderr', 'Saída de erro')], max_length=20, verbose_name='Tipo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_detalhados', to='setup.execucaobackup', verbose_name='Execução do backup')),
            ],
            options={
                'verbose_name': 'Log detalhado da execução',
                'verbose_name_plural': 'Logs detalhados das execuções',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meio', models.CharField(choices=[('email', 'E-mail'), ('telegram', 'Telegram')], max_length=20, verbose_name='Meio de notificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('enviar_sucesso', models.BooleanField(default=False, verbose_name='Enviar em caso de sucesso')),
                ('enviar_falha', models.BooleanField(default=True, verbose_name='Enviar em caso de falha')),
                ('destino_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de destino')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chat ID do Telegram')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='setup.configuracaobackup', verbose_name='Configuração do backup')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
    ]
