# Generated by Django 5.2 on 2025-04-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_agendamentobackup_logexecucaodetalhado_notificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaobackup',
            name='ignorar_arquivos',
        ),
        migrations.CreateModel(
            name='ArquivoIgnorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho', models.CharField(help_text='Informe o caminho do arquivo ou pasta a ser ignorado.', max_length=255, verbose_name='Caminho a ser ignorado')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_ignorados', to='setup.configuracaobackup', verbose_name='Configuração do backup')),
            ],
            options={
                'verbose_name': 'Arquivo/Pasta ignorado(a)',
                'verbose_name_plural': 'Arquivos/Pastas ignorados(as)',
            },
        ),
    ]
