# Generated by Django 5.2 on 2025-05-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_remove_configuracaobackup_ignorar_arquivos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execucaobackup',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Execução do backup', 'verbose_name_plural': 'Execuções dos backups'},
        ),
    ]
